---
- name: Install apache httpd  (state=present is optional)
  become: yes
  hosts: all
  tasks:
      - name: test
        apt:
         name: apache2
         update_cache: yes
         state: present
